### ISSUE TITLE
"PC-UML_Multipilcity"

### ISSUE THREAD

**Issue by odungern** [GfSE/SysML-SpecIF-Bridge#2]
In the [class definitions](https://github.com/GfSE/SysML-SpecIF-Bridge/blob/master/classDefinitions/302_UML_ResourceClasses.specif) the term "PC-UML_Multipilcity" is being used in several places. It seems there is a typo and it should be "PC-UML_Multiplicity".

**Comment by oalt** [comment]
I have fixed the definitions.
