### ISSUE TITLE
Rename and add a column to transformation table

### ISSUE THREAD

**Issue by odungern** [GfSE/SysML-SpecIF-Bridge#3]
Thanks @oalt for preparing the [SysML to SpecIF transformation table](https://github.com/GfSE/SysML-SpecIF-Bridge/wiki/UML-FMC-Mapping-Tables) !

May I suggest:
- to rename column 'SpecIF-Element' by 'SpecIF resourceClass'
- to add a column SpecIF:SubClass to specify the vocabulary term signifying the type of element. 

For example a SysML start event would be assigned a resourceClass named FMC:Event and get a property named 'SpecIF:SubClass' with a value 'SpecIF:startEvent'. The values of 'SpecIF:SubClass' should be used by all modelling notations (SysML, BPMN and others) to allow model integration.

**Comment by oalt** [comment]
Done.
