### ISSUE TITLE
Component is a FMC:Actor

### ISSUE THREAD

**Issue by odungern** [GfSE/SysML-SpecIF-Bridge#4]
wrt [SysML to SpecIF transformation tables](https://github.com/GfSE/SysML-SpecIF-Bridge/wiki/UML-FMC-Mapping-Tables):

An EA-Element.Type 'Component' is a FMC:Actor, because it can be seen as an agent modifying states. Of course, a 'Component' may also internally contain states (= store information), but a piece of software or a mechanical part is best regarded an actor when seen from external (according to my experience or prior usage). A BoM is in my eyes more intuitively seen as a collection of actors than a collection of states.

Let's discuss.

**Comment by oalt** [comment]
In my understanding a component is similar to a class. So why then change the component, but not change the class element?

**Comment by odungern** [comment]
That's a very valid point of view. 
Here, we are in a space where conventions may help. In my project history I found it beneficial to have a means of structuring components, functions and alike ('system elements') in a block diagram, both when using FMC or SysML. Because I also need a means of structuring information elements, I have used UML class diagrams. This is shaky, if a class is attributed a meaning in terms of object orientation, but when you see them as information containers primarily, it leads to the conclusion that a class is a 'SpecIF:State'.
Let's discuss.

**Comment by oalt** [comment]
I can live with both possible solutions. Just lets make a decission.

**Comment by oalt** [comment]
I think one problem is, that UML does not make a difference between an active and passive component as FMC does. In SysML you model all components with the same element - independend if the element is just a database or a database driver.

**Comment by odungern** [comment]
Puhh. Yes, this is a topic we must consider and discuss thoughtfully.
While I see a lot of value in distinguishing 'FMC:Actor', 'FMC:State' and 'FMC:Event', it may not be appropriate to force UML/SysML model elements in those concepts, if there is no such notion in their original definition. So far I have assumed there is an implicit meaning in SysML model elements that can be clearly mapped to the FMC model element types. You are pointing out this is not the case.
So, we might create a special SysML convention with such a notion, but we cannot correctly transform existing SysML models applying the FMC concepts.
I must think a little, now. I still believe that every model element can be clearly assigned to one of the FMC model element types, but if SysML doesn't make the difference, then it is impossible to deduce it automatically at the time of transformation to SpecIF.  Or is there some context information that would allow to make a correct mapping?
What does it boil down to:
- Either, we somehow can correctly map SysML model elements to the FMC model element types. Then it is quite easy to follow the path of model integration, we have started with FMC and BPMN. (In case of BPMN it has been possible to unambiguously assign all model element types to FMC model element types).
- Or we must create a set of special SpecIF classes for SysML model exchange without distinguishing actors and states.

Let's discuss.

**Comment by oalt** [comment]
On the FMC homepage you can find three diagram types:
- Compositional Structure
- Behavior (Petri nets)
- Entity relationship diagrams

In the FMC examples you will fund just the three Elements (rectangular nodes/active, rounded nodes/passive and arcs) but you will find also some more Information in the diagrams:
- cardinalities
- attributes
etc.
How should we handle this in our mapping? In my examples I tried to map some of these extended information to FMC base elements. But I am not sure if the mapping is correct all the time.  

I would prefer a mapping to as less as possible elements taken form FMC and no special SysML approach. Perhaps we have to extend the 3 elements a little? But the most important thing is not to make it to complex.

**Comment by odungern** [comment]
In a phone-call today we have agreed to map UML/SysML classes (as modelled in Class Diagrams) to FMC:State even though a UML class may have methods and may not have attributes, at all. We will see whether this mapping is useful in practice. 
Yes, next to the three classes FMC:Actor/State/Event, there will be others such as IREB:Requirement. So far, we have been successful in using the same general classes for FMC, BPMN and now SysML. Let's continue to try.
