### ISSUE TITLE
Package is a SpecIF:Collection

### ISSUE THREAD

**Issue by odungern** [GfSE/SysML-SpecIF-Bridge#5]
wrt [SysML to SpecIF transformation tables](https://github.com/GfSE/SysML-SpecIF-Bridge/wiki/UML-FMC-Mapping-Tables):

I propose to map a EA-Element.Type 'Package' to a SpecIF resourceClass 'SpecIF:Collection'. This resourceClass is also used by a BPMN 'Group'.

(A SpecIF:Heading is used for headings in documents, in case there is no model element for a logic grouping).

**Comment by oalt** [comment]
@odungern: Where can I fimd the definition of "SpecIF:Collection" it seems not yet included in the class definitions provided in the SpecIF repository?

**Comment by odungern** [comment]
Unfortunately the viewer is down, so please have a look in the [vocabulary file](https://github.com/GfSE/SpecIF-Examples-and-Test-cases/blob/master/vocabulary/SpecIF%20Vocabulary.specif) and search for "SpecIF:Collection".

**Comment by oalt** [comment]
I have extended the class definitions with a SpecIF:Collection and will change the mapping table.
