### ISSUE TITLE
Extend the property set of FMC elements to support mapping of UML and other languages

### ISSUE THREAD

**Issue by oalt** [GfSE/SysML-SpecIF-Bridge#6]
Currently the property set of the FMC resource elements is limited to  three elements (https://github.com/GfSE/SpecIF/blob/master/classDefinitions/03_FMC%20Modeling/403_ResourceClasses.specif)
-  "PC-Name"
- "PC-Text"
- "PC-Status"

To be able to map the UML data to the FMC base elements without using inheritance and new resource classes, the following properties are needed additionally:
1. Visibility Kind (public, protected, private etc.) - not yet a standard property in SpecIF
2. SpecIF:Stereotype
3. dcterms:type - Information of the original metatype (e.g. OMG:UML:2.5.1:Class) - not yet a standard property in SpecIF
4. rdf:value - property to save a value of different meaning, depending on the element type (Attribute Default value, a taggedValue value etc.) - not yet a standard property in SpecIF
5. SpecIF:Alias - an alias Name - not yet a standard property in SpecIF
6. SpecIF:SubClass - The sub-class of the element

I think with these few extensions, the most data of UML elements can be transformed to SpecIF-FMC. @odungern: What do you think?

If you agree, I can extend the class definitions for FMC modeling and the base-property definitions in the SpecIF repository.

**Comment by odungern** [comment]
@oalt: Thanks for your proposals. I think all these make sense ... and I strongly support the reuse of property types from other name spaces. They are all quite generic, so we can include them in the base set of classes.

**Comment by oalt** [comment]
Reopen the issue until update of the class definitions.
