### ISSUE TITLE
SpecIF:precedes/triggers/signals can be combined?

### ISSUE THREAD

**Issue by S-Ruesch** [GfSE/SysML-SpecIF-Bridge#9]
Last week we discussed if the statements SpecIF:preceds, SpecIF:triggers and SpecIF:signals can be combined to one statement. When combined there is no information lost, because the type of the connection is already given by the two resources that are connected together.
One idea was to replace all three statements with the statement SpecIF:signals. Other ideas could be SpecIF:continues, SpecIF:commences or SpecIF:activates. What do you think? Which statement fits best for the application?

**Comment by oalt** [comment]
I vote for triggers!

**Comment by odungern** [comment]
Among others, LEO lists the following translations for 'auslösen':
- activate
- cause
- initiate
- provoke
- produce
- triggers
It must somehow sound right in all situations:
- activity <term> activity
- activity <term> event
- event <term> activity
If we want to use a single term, I think 'initiates' or 'triggers' is acceptable. 
However I do not see a real advantage in combining the terms other than having fewer to deal with. The description won't be as crisp as for the separate terms ... and any translation to natural language will get more abstract, or 'gestelzt', as we would say in German.

**Comment by odungern** [comment]
In a teleconference on Oct/17 with @oalt, @oeichmann,  @S-Ruesch and @odungern  it has been decided to go with all three statement types SpecIF:signals, SpecIF:triggers and SpecIF: precedes. It has been considered useful to distinguish clearly thm for direct semantic analysis by type ... and without further analysis of the context.
